# Generated by Django 4.2.3 on 2023-07-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0002_alter_todo_options_alter_todo_is_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='is_done',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
